config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'site#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products
  resources :users, only: [:index]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin
      can :manage, :all
    else
      can :read, User
      can :manage, Product
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :admin,:password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :admin,:password, :current_password)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :image_url)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  prepend_before_action :require_no_authentication, only: []
  prepend_before_action :authenticate_scope!, only: %i[new edit update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
include ActionView::Helpers::TagHelper
include ActionView::Helpers::NumberHelper
include ActionView::Context
module ProductHelper
  def price(price)
    number_to_currency(price, unit: 'R$')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portabilis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header >
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">
            <i class="fa fa-bank"></i> &nbsp;<strong>Rações Gourmet</strong>
          </a>
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Produtos', products_path, class: 'nav-link' %>
                </li>
                <% if can? :read, User %>
                  <li class="nav-item">
                    <%= link_to 'Usuários', users_path, class: 'nav-link' %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </div>
          <% if user_signed_in? %>
            <div class="dropdown" class="float-right">
              <a class="dropdown-toggle text-info" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li><%= link_to('Editar', edit_user_registration_path(current_user.id), class: 'dropdown-item') %></li>
                <li><%= link_to('Sair', destroy_user_session_path, method: :delete, class: 'dropdown-item') %></li>
              </ul>
            </div>
          <% else %>
             <%= link_to "Entrar", new_user_session_path, class:'text-info' %>
          <% end %>
        </nav>
      </div>
    </header>
    <article>
      <div class="container mt-5">
        <% flash.each do |key, msg| %>
          <div class="alert alert-<%= key == 'alert' ? 'danger' : 'info' %>">
              <div class="alert-text">
                  <h6><%= msg %></h6>
              </div>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </article>
  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
  <%= form_with model: @product do |form| %>
    <div class="form-group mb-3">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control", autofocus: true %>
      <% @product.errors.full_messages_for(:title).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :price %>
      <%= form.text_field :price, class: "form-control", autofocus: true %>
      <% @product.errors.full_messages_for(:price).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

     <div class="form-group mb-3">
      <%= form.label :image_url %>
      <%= form.text_field :image_url, class: "form-control", autofocus: true %>
      <% @product.errors.full_messages_for(:image_url).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control", autofocus: true, rows: 20 %>
      <% @product.errors.full_messages_for(:description).each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
    <%= form.submit class: "btn btn-dark btn-block" %>
  <% end %>
</div>

app/views/products/edit.html.erb
<h3>Editar produto</h3>
<hr/>

<%= render "form"%>

app/views/products/index.html.erb
<h3>
	Produtos
	<%= link_to('Novo produto', new_product_path, class: 'btn btn-primary float-end') %>
</h3>
<br clear="all">
<% if @products.nil? %>
	<div class="alert alert-info">
		Neenhum produto encontrado
	</div>
<% else %>
	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Preço</th>
				<th>#</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.id %></td>
					<td><%= product.title %></td>
					<td><%= price(product.price) %></td>
					<td>
						<div class="dropdown">
						  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
						    Opções
						  </button>
						  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
						    <li><%= link_to('Editar', edit_product_path(product.id), class: 'dropdown-item') %></li>
						    <li><%= link_to('Deletar', product_path(product.id), method: :delete, class: 'dropdown-item', data: {confirm: 'Tem certeza?'}) %></li>
						  </ul>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

app/views/products/new.html.erb
<h3>Novo produto</h3>
<hr/>

<%= render "form" %>

app/views/products/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
    	<%= link_to('Home', root_path) %>
    </li>
    <li class="breadcrumb-item active" aria-current="page"><%= @product.title %></li>
  </ol>
</nav>
<h2>
	<%= @product.title %> <br/>
	<small>Codigo: <%= @product.id %></small>
</h2>
<hr/>
<div class="row">
	<div class="col-md-6">
		<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
		  <div class="carousel-inner">
		  	<% if @product.image_url.present? %>
			    <div class="carousel-item active">
		    		<img src="<%= @product.image_url %>" class="d-block w-100" alt="No image">
		    	</div>
		    <% else %>
		    	<div class="carousel-item active">
		    		<img src="https://thumbs.dreamstime.com/b/no-image-available-icon-vector-illustration-flat-design-140476186.jpg" class="d-block w-100" alt="No image">
		    	</div>
		    <% end %>
		  </div>
		  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
		    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
		    <span class="carousel-control-next-icon" aria-hidden="true"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
	</div>
	<div class="col-md-6">
		<h5>Preço: <%= price(@product.price) %></h5>
		<hr/>
		<h5>Descrição</h5>
		<p><%= simple_format(@product.description) %></p>
	</div>
</div>

app/views/site/index.html.erb
<div class="row">
	<% @products.each do |product| %>
		<div class="col-md-3">
			<div class="card">
		  		<% if product.image_url.present? %>
			  		<img src="<%= product.image_url %>" class="d-block w-100" alt="<%= product.title %>">
			  	<% else %>
			  		<img src="https://thumbs.dreamstime.com/b/no-image-available-icon-vector-illustration-flat-design-140476186.jpg" class="d-block w-100" alt="No image">
			  	<% end %>
			  <div class="card-body">
			    <h5 class="card-title"><%= product.title %></h5>
				<%= price(product.price) %>
			    <%= link_to 'Ver detalhes', product_path(product.id), class: 'btn btn-primary btn-sm' %>
			  </div>
			</div>
		</div>
	<% end %>
</div>

app/views/users/index.html.erb
<h3>
	Usuário
	<% if can? :manage, User %>
		<%= link_to('Novo usuário', new_user_registration_path, class: 'btn btn-primary float-end') %>
	<% end %>
</h3>
<br clear="all">
<% if @users.nil? %>
	<div class="alert alert-info">
		Neenhum usuario encontrado
	</div>
<% else %>
	<table class="table">
		<thead>
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Email</th>
				<th>Role</th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= user.id %></td>
					<td><%= user.name %></td>
					<td><%= user.email %></td>
					<td><%= user.admin ? 'Admin' : 'Operador' %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>